# Makefile for blunt

  lib.name = blunt

  class.sources = blunt.c

  datafiles =

  suppress-wunused = 'yes'
  #optimization.flags = -O0 -ffast-math -funroll-loops -fomit-frame-pointer

  include ../pd-lib-builder/Makefile.pdlibbuilder
