name: Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build on ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1
        with:
          linking-type: shared

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build
